### ISSUE TITLE
Adding track using fileURL to viewConfig gives error

### ISSUE THREAD

**Issue by sonnyarora** [higlass/higlass-server#120]
I'm trying to follow the instructions for adding tracks using the viewConfig. There is a section about adding tracks using a fileURL:

https://docs.higlass.io/view_config.html#tracks

When I try to follow the example given in the docs, I get in the higlass browser: "Unknown track type: vector". If I change the type in the viewConfig to horizontal-line, I only get "Loading..."  in the browser. Here's my viewConfig:

{
  "editable": true,
  "zoomFixed": false,
  "trackSourceServers": [
    "/api/v1",
    "http://higlass.io/api/v1"
  ],
  "exportViewUrl": "/api/v1/viewconfs/",
  "views": [
    {
      "tracks": {
        "top": [
          {
            "type": "horizontal-line",
            "server": "http://higlass.io/api/v1",
            "fileUrl": "http://hgdownload.cse.ucsc.edu/goldenpath/hg19/encodeDCC/wgEncodeSydhTfbs/wgEncodeSydhTfbsGm12878InputStdSig.bigWig",
            "height": 20,
            "uid": "P7PStqTERwSQIYfuiag7Pg",
            "options": {
              "labelColor": "black",
              "labelPosition": "topLeft",
              "labelLeftMargin": 0,
              "labelRightMargin": 0,
              "labelTopMargin": 0,
              "labelBottomMargin": 0,
              "labelBackgroundColor": "white",
              "labelShowResolution": false,
              "axisLabelFormatting": "scientific",
              "axisPositionHorizontal": "right",
              "lineStrokeColor": "blue",
              "lineStrokeWidth": 1,
              "valueScaling": "linear",
              "trackBorderWidth": 0,
              "trackBorderColor": "black",
              "labelTextOpacity": 0.4,
              "showMousePosition": false,
              "mousePositionColor": "#000000",
              "showTooltip": false
            }
          }
        ],
        "left": [],
        "center": [],
        "right": [],
        "bottom": [],
        "whole": [],
        "gallery": []
      },
      "initialXDomain": [
        804790556.208501,
        2395846923.287899
      ],
      "initialYDomain": [
        409150616.7513812,
        2792349941.057543
      ],
      "layout": {
        "w": 12,
        "h": 12,
        "x": 0,
        "y": 0,
        "moved": false,
        "static": false
      },
      "uid": "RdhK3CqOSBOQdROn7DzJkQ"
    }
  ],
  "zoomLocks": {
    "locksByViewUid": {},
    "locksDict": {}
  },
  "locationLocks": {
    "locksByViewUid": {},
    "locksDict": {}
  },
  "valueScaleLocks": {
    "locksByViewUid": {},
    "locksDict": {}
  }
}

Looking in the browser console, I see the following error:

Failed to load resource: the server responded with a status of 500 (Internal Server Error) higlass.io/api/v1/register_url/:1

Error registering url TypeError: Cannot read property 'chromsizes' of null
    at hglib.min.js:1
    at e.<anonymous> (hglib.min.js:8)
    at hglib.min.js:8

Any idea what I'm doing wrong? Thanks in advance.

**Comment by pkerpedjiev** [comment]
Hey, sorry for the delayed reply. We actually don't support the `fileUrl` on the `higlass.io` server.

Would you mind trying to start a server locally using `higlass-manage start` and then amending the  `server:` line above `fileUrl` to point to your local server (e.g. `server: localhost:8989/api/1`)?

**Comment by sonnyarora** [comment]
No worries, thanks for the reply.

I tried on a local server started using higlass-manage. I am still getting the same error. Here's my viewConfig:

**Comment by pkerpedjiev** [comment]
Hey, I just doubled checked and it turns out we don't support this in the docker container. I'm sorry about that.

I created a PR to make that more clear here: https://github.com/higlass/higlass/pull/798

If it becomes more important to you, please let me know and I can see how much effort it would be to add it to the docker container.
