### ISSUE TITLE
Get tilesetuid given uuid

### ISSUE THREAD

**Issue by bnelsj** [higlass/higlass-server#131]
I'm trying to generate viewconfigs in a programmatic way from tracks uploaded to my local server. I can get the UUID from the track name using the uids_by_filename function, but that doesn't include the tilesetuid. Is there a straightforward way to get it given the filename or UUID?

**Comment by pkerpedjiev** [comment]
Hey, I think the UUID is the same as a the tilesetUid. Can you try using it in its place and see if that works for you?

**Comment by bnelsj** [comment]
Hi Peter, thanks for the suggestion. I tried replacing the tilesetUID with the UUID for a heatmap, and got a "No such tileset with uid" error when I loaded the viewconf in the viewer. From what I've seen, the UUID and the tilesetUID are always distinct.

**Comment by pkerpedjiev** [comment]
That's either a bug or something I'm forgetting. Will have to investigate further (hopefully this weekend).

**Comment by pkerpedjiev** [comment]
Hey @bnelsj , I just tried it locally and the UUID returned by `uids_by_filename` is indeed the `tilesetUid`. Here's what I did:

Go to http://localhost:8989/api/v1/uids_by_filename/?d=dixon2012-h1hesc-hindiii-allreps-filtered.1000kb.multires.cool

```
{
   "count":1,
   "results":[
      {
         "uuid":"K_seUJg7TG-ffWvjy8yRsw",
         "filetype":"cooler",
         "datatype":"matrix",
         "private":false,
         "name":"dixon2012-h1hesc-hindiii-allreps-filtered.1000kb.multires.cool",
         "coordSystem":"",
         "coordSystem2":"",
         "created":"2020-04-16T04:15:09.872727Z",
         "project_name":"",
         "project_owner":"",
         "description":""
      }
   ]
}
```

I then created a track with that as the tilesetUid:

```
              {
                "server": "http://localhost:8989/api/v1",
                "tilesetUid": "K_seUJg7TG-ffWvjy8yRsw",
                "uid": "LpAoU5JvQ1qx-hsswzii5Q",
                ...
               }
```

And it loaded fine.

Could you be more specific about your configuration?

**Comment by bnelsj** [comment]
Hi Peter, I was able to reproduce your example. Looks like the problem is that I used the uuid returned by uids_by_filename as the uid and tilesetUid in the viewconf instead of only the tilesetUid. Is the uid optional in viewconfs? What purpose does it serve?

Thanks for the help, and feel free to close this one out.

**Comment by pkerpedjiev** [comment]
So the `tilesetUid` in a track definition identifies data on the server. That's what you get back from the server using the `uids_by_filename` call.

The `uid` in a track identifies the track itself. This is used for a number of things internally the most notable of which is the definition of track "locks" linking value scales.

So you can have two different tracks that have the same `tilesetUid` but you should never have two tracks with the same `uid` (unless they're in separate views, but that's a story for another day :-) )

I hope that makes sense.
