### ISSUE TITLE
chromsizes file is not properly ingested into server database

### ISSUE THREAD

**Issue by Drmirdeep** [higlass/higlass-server#97]
Hi, 

I have installed higlass server 1.7.3 from github and the client v1.3.1 (I cannot use docker at my infrastructure). (Actually, it were the latest git checkouts from Feb. 1st 2019. The version numbers in the changelogs seem not to follow the release version numbers).

I have ingested a chromsizes file and a genome annotation file for hg19 by
python manage.py ingest_tileset --filename chromSizes.tsv --filetype chromsizes-tsv --datatype chromsizes --coordSystem hg19 --name "Chromosomes (hg19)" --uid chromSizes-hg19 --coordSystem2 hg19

and 

python manage.py ingest_tileset --filename gene-annotations-hg19.beddb --filetype beddb --datatype gene-annotation --coordSystem hg19 --name anno_hg19 --uid anno_hg19

However when running client and trying to use the search bar I am not even getting hg19 as a putative species for selection. The dubugger clearly states that it tries to access 
/api/v1/chrom-sizes/ which does not exist likely due to a faulty ingestion procedure. Do you have an idea how to solve it? 

Cheers

**Comment by Drmirdeep** [comment]
server is running on port 8001. client on 8080.
console output hints to chromsizes not found and looks like 
![console_output](https://user-images.githubusercontent.com/27487599/52149017-d2b5d980-266b-11e9-9d53-4feede8e5313.png)


This is the referenced code in GenomePositionSearchBox.js
![line453_in_genompossearchbox](https://user-images.githubusercontent.com/27487599/52149410-eca3ec00-266c-11e9-9658-3cdc7338450f.png)



Current view is minimalistic. The higlass.io as a reference is outcommented and replaced by my local version...
 
{
  "zoomFixed": false,
  "views": [
    {
      "layout": {
        "w": 12,
        "h": 7,
        "x": 0,
        "y": 0,
        "i": "aa",
        "moved": false,
        "static": false
      },
      "uid": "aa",
      "initialYDomain": [
        2538887240.6609,
        2549518368.3142257
      ],
      "autocompleteSource": "/api/v1/suggest/?d=anno_hg19&",
      "initialXDomain": [
        2487716369.15442,
        2603284058.558241
      ],
      "tracks": {
        "left": [],
        "top": [],
        "right": [],
        "center": [],
        "bottom": [],
        "whole": [],
        "gallery": []
      },
      //"chromInfoPath": "//s3.amazonaws.com/pkerp/data/hg19/chromSizes.tsv",
      "chromInfoPath": "http://localhost:8080/chromSizes.tsv",
      "genomePositionSearchBoxVisible": false,
      "genomePositionSearchBox": {
        "visible": true,
        //"chromInfoServer": "http://localhost:8001/api/v1",
        "chromInfoServer": "http://higlass.io/api/v1",
        "chromInfoId": "hg19",
        "autocompleteServer": "http://localhost:8001/api/v1",
        "autocompleteId": "anno_hg19"
      }
    }
  ],
  "editable": true,
  "exportViewUrl": "/api/v1/viewconfs",
  "zoomLocks": {
    "locksByViewUid": {},
    "locksDict": {}
  },
  "trackSourceServers": [
    "http://higlass.io/api/v1",
    "http://localhost:8001/api/v1"
  ],
  "locationLocks": {
    "locksByViewUid": {
      "aa": "PkNgAl3mSIqttnSsCewngw",
      "ewZvJwlDSei_dbpIAkGMlg": "PkNgAl3mSIqttnSsCewngw"
    },
    "locksDict": {
      "PkNgAl3mSIqttnSsCewngw": {
        "aa": [
          1550000000,
          1550000000,
          3380588.876772046
        ],
        "ewZvJwlDSei_dbpIAkGMlg": [
          1550000000.0000002,
          1549999999.9999993,
          3380588.876772046
        ],
        "uid": "PkNgAl3mSIqttnSsCewngw"
      }
    }
  },
  "valueScaleLocks": {
    "locksByViewUid": {},
    "locksDict": {}
  }
}

Thanks for your help!
​

**Comment by Drmirdeep** [comment]
I can also access the tracks on my server and the genome coordinates as well as gene annotations are also visible... However, the genome search box is not working since no genome assembly is available (saying none in the top left corner and nothing there when clicking on it)
![track_example](https://user-images.githubusercontent.com/27487599/52149624-a1d6a400-266d-11e9-9b07-02f3e8b2bdcf.png)

**Comment by Drmirdeep** [comment]
I fixed the issue myself by changing line 315 in GenomePositionSearchBox.js
from 
tileProxy.json(`${sourceServer}/available-chrom-sizes/`, (error, data) => {
to
tileProxy.json(`${sourceServer}/tilesets/`, (error, data) => {

Cheers

**Comment by pkerpedjiev** [comment]
Wow, well done! Would you mind issuing a PR with your change to the higlass repo?

**Comment by pkerpedjiev** [comment]
Also, would you mind posting the last few lines of your /data/log/hgs.log file? I'm curious which internal server error was being thrown.

**Comment by Drmirdeep** [comment]
The log file stated in the settings.py is empty 
However, switching to DEBUG = True in the settings.py I get output on the console
ERROR Internal Server Error: /api/v1/available-chrom-sizes/
ERROR "GET /api/v1/available-chrom-sizes/ HTTP/1.1" 500 17334

Apart from that there is a new issue now which is likely related but in the moment I am not able to fix.

![missing_unique_key_and_cors_request](https://user-images.githubusercontent.com/27487599/52261713-864bf180-292a-11e9-8df9-b70116cfafd5.png)

The CORS one is related to having the server and client on different ports and somewhere it must be specified for the client to allow to get data from a different domain/port...

**Comment by pkerpedjiev** [comment]
That's odd. If there's an Internal Server Error, there should be something in the log file. Is this the one you checked? https://github.com/higlass/higlass-server/blob/develop/higlass_server/settings.py#L142

Which command are you using to run the server?

As for the CORS issue, all CORS requests should be enabled. See here: https://github.com/higlass/higlass-server/blob/50e30f7d1cd0784941597bdfca19373388c1c68d/higlass_server/settings.py#L215

Strange that firefox complains and chrome doesn't. I can spend a little bit of time investigating this evening.

**Comment by pkerpedjiev** [comment]
That is really strange that it's not producing a log file. 

A couple things I can suggest:

1. Take a look at the Dockerfile to see how it's being run by our Docker container: https://github.com/higlass/higlass-docker/blob/master/web-context/Dockerfile.template
2. Use the latest higlass-server version (1.9.1)
